// https://docs.expo.dev/guides/using-eslint/
const { defineConfig } = require('eslint/config');
const expoConfig = require('eslint-config-expo/flat');

module.exports = defineConfig([
  ...expoConfig,
  {
    ignores: [
      'dist/*',
      'public/*',
      '_expo/*',
      'web-build/*',
      'node_modules/*',
      '*.bundle.js',
      '*.bundle.js.map',
      // Generated by `expo start`.
      '.expo/**',
      // Deno edge functions (npm: specifiers), not part of the app bundle.
      'supabase/functions/**',
    ],
  },
  {
    rules: {
      '@typescript-eslint/no-unused-vars': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/prefer-as-const': 'off',
      '@typescript-eslint/no-require-imports': 'off',
      'react/react-in-jsx-scope': 'off',
      '@typescript-eslint/no-empty-object-type': 'off',
      '@typescript-eslint/no-wrapper-object-types': 'off',
      'react/no-unescaped-entities': 'off',
      'import/no-unresolved': 'error',
      'prefer-const': 'off',
      'react/prop-types': 'warn',
      'no-case-declarations': 'off',
      // eslint-plugin-react-hooks 7 added checks that prepare code for React Compiler,
      // which this app doesn't use. They flag patterns that are normal here (an
      // Animated.Value held in a ref and read in render, state reset in an effect)
      // and would need a refactor of the animation code. Turn them back on, and fix
      // what they find, if the compiler is adopted. rules-of-hooks and
      // exhaustive-deps stay on.
      'react-hooks/refs': 'off',
      'react-hooks/set-state-in-effect': 'off',
      'react-hooks/purity': 'off',
      'react-hooks/static-components': 'off',
      'react-hooks/immutability': 'off',
    },
  },
  {
    files: ['metro.config.js'],
    rules: {
      '@typescript-eslint/no-require-imports': 'off',
    },
  },
]);
