// Raises every CocoaPods target to at least the app's iOS deployment target.
//
// Some pods (e.g. RNCAsyncStorage's resource bundle) still declare iOS 13.4.
// Xcode 27 only builds for iOS 15.0 and later, so those targets fail with
// "IPHONEOS_DEPLOYMENT_TARGET is set to 13.4". ios/ is generated by
// `expo prebuild`, so the fix lives here rather than in the Podfile.
const fs = require('fs');
const path = require('path');
const { withDangerousMod } = require('@expo/config-plugins');

const MARKER = '# withMinimumPodsDeploymentTarget';

module.exports = function withMinimumPodsDeploymentTarget(config, { minimum = '15.1' } = {}) {
    return withDangerousMod(config, [
        'ios',
        (cfg) => {
            const podfilePath = path.join(cfg.modRequest.platformProjectRoot, 'Podfile');
            let podfile = fs.readFileSync(podfilePath, 'utf8');
            if (podfile.includes(MARKER)) return cfg;

            const hook = 'post_install do |installer|';
            if (!podfile.includes(hook)) {
                throw new Error(`withMinimumPodsDeploymentTarget: no "${hook}" in Podfile`);
            }
            podfile = podfile.replace(
                hook,
                `${hook}
    ${MARKER}
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_config|
        current = build_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
        if current.nil? || Gem::Version.new(current) < Gem::Version.new('${minimum}')
          build_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '${minimum}'
        end
      end
    end
`
            );
            fs.writeFileSync(podfilePath, podfile);
            return cfg;
        },
    ]);
};
