// Turns off Xcode's user script sandboxing for the app project.
//
// The generated project sets ENABLE_USER_SCRIPT_SANDBOXING = YES, and Xcode 27
// enforces it: CocoaPods' "[CP] Copy Pods Resources" phase then fails writing
// ios/Pods/resources-to-copy-<target>.txt, which it doesn't declare as an
// output. ios/ is generated by `expo prebuild`, so the setting lives here.
const { withXcodeProject } = require('@expo/config-plugins');

module.exports = function withUserScriptSandboxingDisabled(config) {
    return withXcodeProject(config, (cfg) => {
        const configurations = cfg.modResults.pbxXCBuildConfigurationSection();
        for (const key of Object.keys(configurations)) {
            const buildSettings = configurations[key].buildSettings;
            if (buildSettings) buildSettings.ENABLE_USER_SCRIPT_SANDBOXING = 'NO';
        }
        return cfg;
    });
};
