// Adopts the UIScene lifecycle in the generated iOS app.
//
// iOS 27 terminates apps built with the iOS 27 SDK that don't adopt UIScene
// (SIGTRAP in _UIApplicationEvaluateRuntimeIssueForNoSceneLifecycleAdoption).
// Expo SDK 54's template creates its window in AppDelegate, so this plugin:
// - declares a single-window scene configuration in Info.plist,
// - adds SceneDelegate.swift, which creates the window and starts React Native,
// - stops AppDelegate from creating a window of its own.
//
// Temporary: remove once the Expo SDK's template adopts UIScene itself.
const fs = require('fs');
const path = require('path');
const {
    IOSConfig,
    withAppDelegate,
    withDangerousMod,
    withInfoPlist,
    withXcodeProject,
} = require('@expo/config-plugins');

const SCENE_DELEGATE = `// Generated by plugins/withSceneLifecycle.js — edit the plugin, not this file.
import UIKit
import React

class SceneDelegate: UIResponder, UIWindowSceneDelegate {
  var window: UIWindow?

  private var appDelegate: AppDelegate? {
    UIApplication.shared.delegate as? AppDelegate
  }

  func scene(
    _ scene: UIScene,
    willConnectTo session: UISceneSession,
    options connectionOptions: UIScene.ConnectionOptions
  ) {
    guard let windowScene = scene as? UIWindowScene,
          let appDelegate = appDelegate,
          let factory = appDelegate.reactNativeFactory else { return }

    let window = UIWindow(windowScene: windowScene)
    self.window = window
    appDelegate.window = window

    // A cold-start link arrives on the connection options, not launch options.
    var launchOptions: [UIApplication.LaunchOptionsKey: Any] = [:]
    if let url = connectionOptions.urlContexts.first?.url {
      launchOptions[.url] = url
    }

    factory.startReactNative(withModuleName: "main", in: window, launchOptions: launchOptions)
  }

  // Links opened while running: route through AppDelegate's existing handlers.
  func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) {
    guard let url = URLContexts.first?.url else { return }
    _ = appDelegate?.application(UIApplication.shared, open: url, options: [:])
  }

  func scene(_ scene: UIScene, continue userActivity: NSUserActivity) {
    _ = appDelegate?.application(UIApplication.shared, continue: userActivity, restorationHandler: { _ in })
  }
}
`;

// The template's window creation in application(_:didFinishLaunchingWithOptions:).
const APP_DELEGATE_WINDOW_BLOCK =
    /#if os\(iOS\) \|\| os\(tvOS\)\s*\n\s*window = UIWindow\(frame: UIScreen\.main\.bounds\)\s*\n\s*factory\.startReactNative\([\s\S]*?\)\s*\n#endif\s*\n/;

module.exports = function withSceneLifecycle(config) {
    config = withInfoPlist(config, (cfg) => {
        cfg.modResults.UIApplicationSceneManifest = {
            UIApplicationSupportsMultipleScenes: false,
            UISceneConfigurations: {
                UIWindowSceneSessionRoleApplication: [
                    {
                        UISceneConfigurationName: 'Default Configuration',
                        UISceneDelegateClassName: '$(PRODUCT_MODULE_NAME).SceneDelegate',
                    },
                ],
            },
        };
        return cfg;
    });

    config = withAppDelegate(config, (cfg) => {
        if (cfg.modResults.language !== 'swift') {
            throw new Error('withSceneLifecycle: expected a Swift AppDelegate');
        }
        const contents = cfg.modResults.contents;
        if (contents.includes('SceneDelegate starts React Native')) return cfg;
        if (!APP_DELEGATE_WINDOW_BLOCK.test(contents)) {
            throw new Error('withSceneLifecycle: AppDelegate window setup not found; the template changed');
        }
        cfg.modResults.contents = contents.replace(
            APP_DELEGATE_WINDOW_BLOCK,
            '    // SceneDelegate starts React Native in the scene\'s window (UIScene lifecycle).\n'
        );
        return cfg;
    });

    config = withDangerousMod(config, [
        'ios',
        (cfg) => {
            const projectName = IOSConfig.XcodeUtils.getProjectName(cfg.modRequest.projectRoot);
            const file = path.join(cfg.modRequest.platformProjectRoot, projectName, 'SceneDelegate.swift');
            fs.writeFileSync(file, SCENE_DELEGATE);
            return cfg;
        },
    ]);

    config = withXcodeProject(config, (cfg) => {
        const projectName = IOSConfig.XcodeUtils.getProjectName(cfg.modRequest.projectRoot);
        const filepath = `${projectName}/SceneDelegate.swift`;
        if (!cfg.modResults.hasFile(filepath)) {
            IOSConfig.XcodeUtils.addBuildSourceFileToGroup({
                filepath,
                groupName: projectName,
                project: cfg.modResults,
            });
        }
        return cfg;
    });

    return config;
};
